
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Download, Printer, Share2 } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { ContextualHelp } from "@/components/common/ContextualHelp";

// Sample reports data
const sampleReports = [
  {
    id: "RPT-2025-001",
    patientId: "PT-2025-001",
    patientName: "John Doe",
    type: "Diagnostic Summary",
    generatedDate: "2025-04-02",
    generatedBy: "Dr. Smith",
  },
  {
    id: "RPT-2025-002",
    patientId: "PT-2025-001",
    patientName: "John Doe",
    type: "Treatment Plan",
    generatedDate: "2025-04-02",
    generatedBy: "Dr. Smith",
  },
  {
    id: "RPT-2025-003",
    patientId: "PT-2025-002",
    patientName: "Sarah Miller",
    type: "Diagnostic Summary",
    generatedDate: "2025-04-01",
    generatedBy: "Dr. Johnson",
  },
  {
    id: "RPT-2025-004",
    patientId: "PT-2025-003",
    patientName: "Robert Johnson",
    type: "Follow-up Analysis",
    generatedDate: "2025-03-28",
    generatedBy: "Dr. Wilson",
  }
];

export default function ReportsPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Medical Reports"
        description="Generate and manage patient diagnostic reports"
      />

      <Card>
        <CardHeader>
          <CardTitle className="flex justify-between items-center">
            <span>Generated Reports</span>
            <ContextualHelp
              title="Reports Management"
              content="View all generated reports, download them in various formats, or share them securely with patients or other healthcare providers."
            />
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="all" className="space-y-4">
            <TabsList>
              <TabsTrigger value="all">All Reports</TabsTrigger>
              <TabsTrigger value="diagnostic">Diagnostic</TabsTrigger>
              <TabsTrigger value="treatment">Treatment Plans</TabsTrigger>
              <TabsTrigger value="followup">Follow-ups</TabsTrigger>
            </TabsList>
            
            <TabsContent value="all" className="space-y-4">
              <div className="rounded-md border">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Report ID</TableHead>
                      <TableHead>Patient</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Generated Date</TableHead>
                      <TableHead>Generated By</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {sampleReports.map((report) => (
                      <TableRow key={report.id}>
                        <TableCell className="font-medium">{report.id}</TableCell>
                        <TableCell>{report.patientName}</TableCell>
                        <TableCell>{report.type}</TableCell>
                        <TableCell>{report.generatedDate}</TableCell>
                        <TableCell>{report.generatedBy}</TableCell>
                        <TableCell className="text-right">
                          <div className="flex justify-end gap-2">
                            <Button variant="outline" size="sm" className="h-8 w-8 p-0">
                              <Printer className="h-4 w-4" />
                            </Button>
                            <Button variant="outline" size="sm" className="h-8 w-8 p-0">
                              <Download className="h-4 w-4" />
                            </Button>
                            <Button variant="outline" size="sm" className="h-8 w-8 p-0">
                              <Share2 className="h-4 w-4" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </TabsContent>
            
            <TabsContent value="diagnostic">
              <div className="p-4 text-center text-muted-foreground border rounded-md">
                Filter applied for diagnostic reports
              </div>
            </TabsContent>
            
            <TabsContent value="treatment">
              <div className="p-4 text-center text-muted-foreground border rounded-md">
                Filter applied for treatment plans
              </div>
            </TabsContent>
            
            <TabsContent value="followup">
              <div className="p-4 text-center text-muted-foreground border rounded-md">
                Filter applied for follow-up reports
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  );
}
